version: 1
frontend:
  phases:
    preBuild:
      commands:
        - cd ${var.frontend_dir}
        - npm ci
    build:
      commands:
        - npm run build
  artifacts:
    baseDirectory: ${var.frontend_dir}/out
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*