version: 1
frontend:
  phases:
    preBuild:
      commands:
        - echo Skipping pre-build for backend app
    build:
      commands:
        - cd python-app
        - docker build -t python-app .
  artifacts:
    baseDirectory: /
    files:
      - '**/*'
